############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Sur moi"
url = "about/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4

[[main]]
name = "Projets"
url = "blog/"
weight = 2


[[main]]
weight = 5
name = "Pages"
hasChildren = true


[[main]]
parent = "Pages"
name = "Authors"
url = "authors/"

[[main]]
parent = "Pages"
name = "Categories"
url = "categories/"

[[main]]
parent = "Pages"
name = "404 Page"
url = "404/"

[[main]]
parent = "Pages"
name = "Elements"
url = "elements/"


# footer menu
[[footer]]
name = "Sur moi"
url = "about/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Projets"
url = "blog/"
weight = 3


[[footer]]
name = "Mention légales"
url = "privacy-policy/"
weight = 4
